name: isofit_env

channels: &id1
    - http://conda.anaconda.org/conda-forge

dependencies:
    - python=3.*.*
    - pip
    - protobuf~=3.19.0
    - scipy>=1.3.0
    - matplotlib>=2.2.2
    - scikit-learn>=0.19.1
    - scikit-image>=0.17.0
    - spectral>=0.19
    - pytest>=3.5.1
    - pep8>=1.7.1
    - pyyaml>=5.1.2
    - pandas>=0.24
    - gdal>=2.0.0
    - tensorflow>=2.0.1

    - pip:
      - xxhash>=1.2.0
      - ray>=1.2.0
      - ndsplines==0.1.2
