{% set name = "isofit" %}
{% set version = "2.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/isofit/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 045f5600a3e089a01cf5d890fb092909de9df9c62acea95317a1dc1d495d8e32 

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - setuptools
    - numpy >=1.11
    - scipy >=1.1.0
    - numba >=0.38.0
    - matplotlib >=2.2.2
    - scikit-learn >=0.19.1
    - scikit-image >=0.16.2
    - spectral >=0.19
    - pytest >=3.5.1
    - pep8 >=1.7.1
    - python-xxhash >=1.2.0
    - pyyaml >=5.3.1

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/{{ name }}/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Imaging Spectrometer Optimal FITting (ISOFIT)'
  description: |
    ISOFIT provides routines and utilities for fitting surface, atmosphere
    and instrument models to imaging spectrometer data
  dev_url: https://github.com/{{ name }}/{{ name }}
  doc_url: https://github.com/{{ name }}/{{ name }}/wiki
  doc_source_url: https://github.com/{{ name }}/{{ name }}/tree/master/docs

extra:
  recipe-maintainers:
    - adam-erickson
    - winstonolson
    - davidraythompson
    - pgbrodrick
