name: Example Tests

on: [push, pull_request]

jobs:
  examples:
    runs-on: ubuntu-latest
    container:
      image: pgbrodrick/isofit

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Isofit
      run: |
        pip3 install --editable .

    - name: Download and compile 6Sv
      run: |
        cd examples/
        wget -nv https://github.com/ashiklom/isofit/releases/download/6sv-mirror/6sv-2.1.tar
        mkdir -p 6sv-2.1
        tar -xf 6sv-2.1.tar --directory 6sv-2.1
        cd 6sv-2.1
        # Necessary for compilation to work with recent GCC versions
        sed -i Makefile -e 's/FFLAGS.*/& -std=legacy/'
        make

    - name: Download sRTMnet
      run: |
        cd examples/
        mkdir sRTMnet_v100
        cd sRTMnet_v100
        wget -nv https://zenodo.org/record/4096627/files/sRTMnet_v100.zip
        unzip sRTMnet_v100.zip && rm sRTMnet_v100.zip

    # - name: Running Example - image_cube/small
    #   run: |
    #     export SIXS_DIR=$(readlink -f examples/6sv-2.1)
    #     export EMULATOR_PATH=$(readlink -f examples/sRTMnet_v100/sRTMnet_v100)
    #     cd examples/image_cube
    #     echo "SIXS_DIR=$SIXS_DIR"
    #     echo "EMULATOR_PATH=$EMULATOR_PATH"
    #     bash run_small.sh
    #
    # - name: Running Example - image_cube/medium
    #   run: |
    #     export SIXS_DIR=$(readlink -f examples/6sv-2.1)
    #     export EMULATOR_PATH=$(readlink -f examples/sRTMnet_v100/sRTMnet_v100)
    #     cd examples/image_cube
    #     bash run_medium.sh

    - name: Running Example - 20151026_SantaMonica
      run: |
        export SIXS_DIR=$(readlink -f examples/6sv-2.1)
        export EMULATOR_PATH=$(readlink -f examples/sRTMnet_v100/sRTMnet_v100)
        cd examples/20151026_SantaMonica
        bash run_examples.sh

    - name: Running Example - 20171108_Pasadena
      run: |
        export SIXS_DIR=$(readlink -f examples/6sv-2.1)
        export EMULATOR_PATH=$(readlink -f examples/sRTMnet_v100/sRTMnet_v100)
        cd examples/20171108_Pasadena
        bash run_example_libradtran.sh
        bash run_example_modtran.sh
        python run_topoflux_example.py

    - name: Running Example - 20190806_ThermalIR
      run: |
        export SIXS_DIR=$(readlink -f examples/6sv-2.1)
        export EMULATOR_PATH=$(readlink -f examples/sRTMnet_v100/sRTMnet_v100)
        cd examples/20190806_ThermalIR
        python run_example_modtran_one.py
