name: Main Tests

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Isofit
      run: |
        python -m pip install --upgrade pip
        pip install --editable . --use-feature=2020-resolver

    - name: Check Utils
      run: |
        python -c 'from isofit.utils import add_HRRR_profiles_to_modtran_config.py'
        python -c 'from isofit.utils import apply_oe.py'
        python -c 'from isofit.utils import empirical_line.py'
        python -c 'from isofit.utils import extractions.py'
        python -c 'from isofit.utils import instrument_model.py'
        python -c 'from isofit.utils import path.py'
        python -c 'from isofit.utils import remap.py'
        python -c 'from isofit.utils import segment.py'
        python -c 'from isofit.utils import surface_model.py'
