# Install ISOFIT with '$ pip' and run tests in a manner that also leverage's
# the Ubuntu package ecosystem.

name: Test Ubuntu Pip Package

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  ubuntu_matrix:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install non-Python dependencies
      run: |
        sudo apt-get install python3-gdal

    - name: Set up Python virtual environment
      run: |
        sudo apt-get install python3
        python3 -m venv venv --system-site-packages

    - name: Install ISOFIT and dependencies
      run: |
        venv/bin/python pip install ".[dev]"

    - name: Run tests
      run: |
        pytest -k "not cli"
