name: Main Tests

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'
    
    - name: Install GDAL
      run: |
        sudo add-apt-repository ppa:ubuntugis/ppa && sudo apt-get update
        sudo apt-get install gdal-bin
        sudo apt-get install libgdal-dev
        export PYTHONPATH=${PYTHONPATH}:/usr/lib/python3/dist-packages/osgeo:/usr/lib/python3/dist-packages/osgeo_utils:/usr/bin
        export PATH=${PATH}:/usr/lib/python3/dist-packages/osgeo:/usr/lib/python3/dist-packages/osgeo_utils
        pip install GDAL==`gdal-config --version`

    - name: Install Isofit
      run: |
        pip install --editable .

    - name: Check Utils
      run: |
        python -c 'from isofit.utils import apply_oe'
        python -c 'from isofit.utils import empirical_line'
        python -c 'from isofit.utils import extractions'
        python -c 'from isofit.utils import instrument_model'
        python -c 'from isofit.utils import path'
        python -c 'from isofit.utils import remap'
        python -c 'from isofit.utils import segment'
        python -c 'from isofit.utils import surface_model'

    - name: Run Test
      run: |
        pytest
