name: Main Tests

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: osgeo/gdal:ubuntu-full-3.4.0

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Isofit
      run: |
        python3 -m pip install --upgrade pip
        pip3 install GDAL==`gdal-config --version`
        pip3 install --editable .

    - name: Check Utils
      run: |
        python3 -c 'from isofit.utils import apply_oe'
        python3 -c 'from isofit.utils import empirical_line'
        python3 -c 'from isofit.utils import extractions'
        python3 -c 'from isofit.utils import instrument_model'
        python3 -c 'from isofit.utils import path'
        python3 -c 'from isofit.utils import remap'
        python3 -c 'from isofit.utils import segment'
        python3 -c 'from isofit.utils import surface_model'

    - name: Run Test
      run: |
        pytest
