name: Main Tests

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: osgeo/gdal:ubuntu-full-3.4.0

    steps:
    - uses: actions/checkout@v2

    - name: Install Isofit
      run: |
        python -m pip install --upgrade pip
        pip install --editable .

    - name: Check Utils
      run: |
        python -c 'from isofit.utils import apply_oe'
        python -c 'from isofit.utils import empirical_line'
        python -c 'from isofit.utils import extractions'
        python -c 'from isofit.utils import instrument_model'
        python -c 'from isofit.utils import path'
        python -c 'from isofit.utils import remap'
        python -c 'from isofit.utils import segment'
        python -c 'from isofit.utils import surface_model'

    - name: Run Test
      run: |
        pytest
