name: Utils

on: [push, pull_request]

jobs:
  utils:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install GDAL
      run: |
        sudo add-apt-repository ppa:ubuntugis/ppa && sudo apt-get update
        sudo apt-get install gdal-bin
        sudo apt-get install libgdal-dev
        pip install --global-option=build_ext --global-option="-I/usr/include/gdal" GDAL==`gdal-config --version`

    - name: Install Isofit
      run: |
        python -m pip install --upgrade pip
        pip install --editable . --use-feature=2020-resolver

    - name: Run Test
      run: |
        pytest